name: Generate GitHub Summary Cards

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate summary cards
        uses: vn7n24fzkq11/github-profile-summary-cards@release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: sachin-iam
          theme: rose_pine
